services:
  alphavids:
    image: ${REGISTRY}/${IMAGE}
    networks:
      - internal-network
    volumes:
      - videos:/videos
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 10s
      timeout: 2s
      retries: 3 
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  videos:

networks:
  internal-network:
    external: true
