global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]
  
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
  
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080
  
  - job_name: "docker-replicas"
    scrape_interval: 15s
    static_configs:
      - targets: ["replicas-exporter:9258"]