version: '3.4'

services:
  traefik:
    image: traefik:3.2  
    ports:
      - 80:80
      - 443:443
    networks:
      - backend-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=true
    volumes:
      - acmes:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      # - --log.level=DEBUG

      - --entrypoints.web.address=:80

      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedByDefault=false
      - --providers.swarm.network=backend-network

volumes:
  acmes:

networks:
  backend-network:
    external: true