version: '3.7'

services:
  grafana:
    image: grafana/grafana:10.3.7
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD}
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend-network
    configs:
      - source: grafana_config
        target: /etc/grafana/provisioning/datasources/datasources.yaml

volumes:
  grafana_data:

networks:
  backend-network:
    external: true

configs:
  grafana_config:
    name: grafana-datasources-${VERSION}.yaml
    file: ./grafana-datasources.yaml
