name: Build ffmpeg

on:
  push:
    tags:
      - 'ffmpeg/v*'

env:
  REGISTRY: ghcr.io
  IMAGE:  ${{ github.repository }}/ffmpeg

jobs:
  build:
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: | 
            ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: | 
            type=match,pattern=ffmpeg/v(.*),group=1

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ffmpeg
          push: true
          tags: ${{ steps.meta.outputs.tags }}